# =====================================================================
# Configuración de SonarQube para discovery-server (Convivo)
# =====================================================================

sonar.projectKey=convivo_discovery-server
sonar.projectName=Convivo - Discovery Server
sonar.projectVersion=0.4.0

sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/.scannerwork/**

sonar.host.url=http://localhost:9000
